FROM nvidia/cuda:11.1.1-cudnn8-devel-ubuntu20.04

ENV DEBIAN_FRONTEND noninteractive
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

############################ USER ###############################
# setup environment
ENV DEBIAN_FRONTEND=noninteractive
ENV SHELL=/bin/bash \
    USER=arg \
    NB_UID=1000 \
    LANG=en_US.UTF-8 \
    LANGUAGE=en_US.UTF-8

ENV HOME=/home/${USER}

RUN adduser --disabled-password \
    --gecos "Default user" \
    --uid ${NB_UID} \
    ${USER}

RUN echo "root:root" | chpasswd
RUN echo "${USER}:111111" | chpasswd

###################################### basic tools #####################################

RUN apt-get -o Acquire::ForceIPv4=true update && apt-get -yq dist-upgrade \
    && apt-get -o Acquire::ForceIPv4=true install -yq --no-install-recommends \
    locales \
    git \
    vim \
    gedit \
    lsb-release \
    wget \
    sudo \
    build-essential \
    dirmngr \
    gnupg2 \
    unzip \
    mercurial \
    net-tools \
    zip \
    ca-certificates \
    ninja-build \
    protobuf-compiler \
    libprotobuf-dev \
    python-gobject \
    python-tk \
    libcanberra-gtk-module \
    libcanberra-gtk3-module \
    python3-pip \
    python3-setuptools \
    python3-numpy \
    python3-empy  \
    python3-dev \
    python3-opencv \
    python3-venv \
    python3-tk \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

##################################### PIP ######################################

RUN pip3 install --upgrade pip

RUN pip3 install \
    jupyter \
    jupyter_http_over_ws

RUN jupyter serverextension enable --py jupyter_http_over_ws

RUN pip3 install \
    setuptools==59.5.0 \
    cmake \
    numpy \
    cython \
    pandas \
    image \
    Pillow \
    empy \
    nbdev \
    gdown \
    matplotlib \
    tensorflow \
    tensorboard \
    onnx \
    fairscale \
    arg_robotics_tools \
    twine

RUN pip install \
    torch==1.10 \
    torchvision==0.11.1 \
    -f https://download.pytorch.org/whl/cu111/torch_stable.html

##################################### gym #####################################
RUN pip3 install gym[all]==0.26.0

##################################### vim-python-ide ######################################
# RUN git clone https://github.com/ARG-NCTU/vim-python-ide.git && \
#     cd vim-python-ide && ./install.sh


##################################### setting #####################################
RUN chown -R ${USER}:${USER} ${HOME}/
RUN echo "arg ALL=(ALL)  ALL" > /etc/sudoers

# Support of nvidia-docker 2.0
ENV NVIDIA_VISIBLE_DEVICES=all
ENV NVIDIA_DRIVER_CAPABILITIES=all

# COPY ./colab_jupyter.sh /home/arg/

USER ${USER}

WORKDIR ${HOME}

CMD ["jupyter", "notebook", "--port=8888", "--no-browser", "--ip=0.0.0.0", "--allow-root"]
